# Generated by Django 5.2.12 on 2026-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('platform', models.CharField(max_length=64, verbose_name='平台')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('url', models.URLField(verbose_name='链接')),
                ('detail', models.TextField(blank=True, verbose_name='详情')),
                ('section', models.CharField(blank=True, max_length=64, verbose_name='栏目')),
                ('ranktime', models.CharField(blank=True, max_length=32, verbose_name='榜单时间范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
                'db_table': 'info',
                'ordering': ['-date', '-rank'],
                'indexes': [models.Index(fields=['platform', 'date'], name='info_platfor_2942d7_idx'), models.Index(fields=['platform', 'ranktime'], name='info_platfor_bf88d9_idx'), models.Index(fields=['section'], name='info_section_0fcd44_idx')],
            },
        ),
    ]
