# Generated by Django 5.2.12 on 2026-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.URLField(max_length=500, verbose_name='链接'),
        ),
    ]
