# Generated by Django 5.2.12 on 2026-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0002_alter_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='链接'),
        ),
    ]
