# Generated by Django 5.2.12 on 2026-03-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0003_alter_info_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_time', models.DateTimeField(verbose_name='分析时间')),
                ('group', models.CharField(max_length=20, verbose_name='分组')),
                ('article_count', models.IntegerField(verbose_name='文章数')),
                ('platform_count', models.IntegerField(verbose_name='平台数')),
                ('platforms', models.TextField(verbose_name='平台列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '关键词分析',
                'verbose_name_plural': '关键词分析',
                'db_table': 'keyword_analysis',
                'ordering': ['-analysis_time'],
                'indexes': [models.Index(fields=['analysis_time', 'group'], name='keyword_ana_analysi_599ee9_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='关键词')),
                ('score', models.FloatField(verbose_name='得分')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('count', models.IntegerField(verbose_name='出现次数')),
                ('platform_count', models.IntegerField(verbose_name='覆盖平台数')),
                ('coverage', models.FloatField(verbose_name='覆盖率')),
                ('sources', models.TextField(verbose_name='来源平台')),
                ('sample_articles', models.TextField(verbose_name='示例文章')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='parser_api.keywordanalysis')),
            ],
            options={
                'verbose_name': '关键词结果',
                'verbose_name_plural': '关键词结果',
                'db_table': 'keyword_result',
                'indexes': [models.Index(fields=['analysis', 'rank'], name='keyword_res_analysi_c82fa0_idx'), models.Index(fields=['keyword'], name='keyword_res_keyword_c9a9ae_idx')],
            },
        ),
    ]
