# Generated by Django 5.2.12 on 2026-03-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0004_keywordanalysis_keywordresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPhraseExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_time', models.DateTimeField(verbose_name='分析时间')),
                ('extracted_phrases', models.TextField(verbose_name='原文短语')),
                ('normalized_phrases', models.TextField(verbose_name='规范化短语')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_phrases', to='parser_api.info')),
            ],
            options={
                'verbose_name': 'LLM短语提取',
                'verbose_name_plural': 'LLM短语提取',
                'db_table': 'llm_phrase_extraction',
                'indexes': [models.Index(fields=['article', 'analysis_time'], name='llm_phrase__article_d1c91d_idx'), models.Index(fields=['analysis_time'], name='llm_phrase__analysi_cf5c17_idx')],
            },
        ),
    ]
