# Generated by Django 5.2.12 on 2026-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0005_llmphraseextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMBatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_time', models.DateTimeField(verbose_name='分析时间')),
                ('group', models.CharField(max_length=20, verbose_name='分组')),
                ('batch_index', models.IntegerField(verbose_name='批次序号')),
                ('title_count', models.IntegerField(verbose_name='输入标题数')),
                ('input_titles', models.TextField(verbose_name='输入标题')),
                ('output_raw', models.TextField(verbose_name='LLM原始输出')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM批次日志',
                'verbose_name_plural': 'LLM批次日志',
                'db_table': 'llm_batch_log',
                'ordering': ['-analysis_time', 'batch_index'],
                'indexes': [models.Index(fields=['analysis_time', 'group'], name='llm_batch_l_analysi_7ec89d_idx')],
            },
        ),
    ]
