# Generated by Django 5.2.12 on 2026-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0006_add_llm_batch_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMPhraseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_time', models.DateTimeField(verbose_name='分析时间')),
                ('group', models.CharField(max_length=20, verbose_name='分组')),
                ('representative', models.CharField(max_length=200, verbose_name='代表短语')),
                ('members', models.TextField(verbose_name='成员短语列表')),
                ('article_ids', models.TextField(verbose_name='关联文章ID')),
                ('article_count', models.IntegerField(verbose_name='关联文章数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM短语归纳组',
                'verbose_name_plural': 'LLM短语归纳组',
                'db_table': 'llm_phrase_group',
                'indexes': [models.Index(fields=['analysis_time', 'group'], name='llm_phrase__analysi_9125aa_idx'), models.Index(fields=['representative'], name='llm_phrase__represe_3b2b57_idx')],
            },
        ),
    ]
