# Generated by Django 5.2.12 on 2026-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_api', '0007_add_llm_phrase_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('task_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='任务名')),
                ('locked_at', models.DateTimeField(verbose_name='加锁时间')),
                ('worker_id', models.CharField(blank=True, max_length=64, verbose_name='Worker标识')),
            ],
            options={
                'verbose_name': '调度器锁',
                'verbose_name_plural': '调度器锁',
                'db_table': 'scheduler_lock',
            },
        ),
    ]
